net: netfilter: nf_conntrack_core.c: delete unused variable
../net/netfilter/nf_conntrack_core.c:653:16: error: unused variable 'flags' [-Werror,-Wunused-variable]
        unsigned long flags=0;
                      ^
../net/netfilter/nf_conntrack_core.c:1715:16: error: unused variable 'flags' [-Werror,-Wunused-variable]
        unsigned long flags=0;
                      ^